# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0

apiVersion: meta.pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: vpc-composition
  annotations:
    provider: provider-jet-aws
spec:
  crossplane:
    version: ">=v1.0.0"
  dependsOn:
    - provider: crossplane/provider-jet-aws
      version: ">=v0.4.0"
