apiVersion: identity.aws.crossplane.io/v1beta1
kind: IAMRole
metadata:
  name: rediscluster-example-application
spec:
  forProvider:
    description: IAM role created by Crossplane automated
    assumeRolePolicyDocument: | {
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "",
            "Effect": "Allow",
            "Principal": {
                "Federated": "arn:aws:iam::12345:oidc-provider/oidc.eks.us-east-1.amazonaws.com/id/DEADBEEF123"
            },
            "Action": "sts:AssumeRoleWithWebIdentity",
            "Condition": {
                "StringLike": {
                    "oidc.eks.us-east-1.amazonaws.com/id/DEADBEEF123:sub": "system:serviceaccount:preview:rediscluster-example-application"
                }
            }
        }
    ]
}
    region: us-east-1
    
  providerConfigRef:
    name: my-aws-provider
