apiVersion: awsblueprints.io/v1alpha1
kind: RedisCluster
metadata:
  name: rediscluster-example
spec:
  resourceConfig:
    port: 6380
    region: us-east-1
    size: medium
    subnetIds:
      - subnet-abcd123
      - subnet-123abcd
  providerConfigRef:
    name: my-aws-provider
