apiVersion: v1
kind: ServiceAccount
metadata:
  name: &name rediscluster-example-application
  labels:
    name: *name
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::12345:role/rediscluster-example-application
